/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Autocomplete: typeof import('./src/components/Form/Autocomplete.vue')['default']
    BtnFacebook: typeof import('./src/components/Auth/BtnFacebook.vue')['default']
    BtnGoogle: typeof import('./src/components/Auth/BtnGoogle.vue')['default']
    Btntext: typeof import('./src/components/M/Btntext.vue')['default']
    BtnToggleTheme: typeof import('./src/components/Header/BtnToggleTheme.vue')['default']
    CambiarIdioma: typeof import('./src/components/CambiarIdioma.vue')['default']
    Collapse: typeof import('./src/components/Side/Nav/Collapse/Collapse.vue')['default']
    DialogCode: typeof import('./src/components/Auth/DialogCode.vue')['default']
    DialogCodeRecoverPass: typeof import('./src/components/Auth/DialogCodeRecoverPass.vue')['default']
    Group: typeof import('./src/components/Side/Nav/Group/Group.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Page/Home.vue')['default']
    Icon: typeof import('./src/components/Side/Nav/Icon.vue')['default']
    Input: typeof import('./src/components/Form/Input.vue')['default']
    InputFile: typeof import('./src/components/Form/InputFile.vue')['default']
    InputFileDirect: typeof import('./src/components/Form/InputFileDirect.vue')['default']
    InputSingleImage: typeof import('./src/components/Form/InputSingleImage.vue')['default']
    Item: typeof import('./src/components/Side/Nav/Item/Item.vue')['default']
    LoginForm: typeof import('./src/components/Auth/LoginForm.vue')['default']
    Logo: typeof import('./src/components/Logo/Logo.vue')['default']
    LogoDark: typeof import('./src/components/Logo/LogoDark.vue')['default']
    LogoLight: typeof import('./src/components/Logo/LogoLight.vue')['default']
    MdInput: typeof import('./src/components/Form/MdInput.vue')['default']
    MultiInput: typeof import('./src/components/Form/MultiInput.vue')['default']
    MultiInputFile: typeof import('./src/components/Form/MultiInputFile.vue')['default']
    Mundo: typeof import('./src/components/Hola/Mundo.vue')['default']
    NavIcon: typeof import('./src/components/Header/NavIcon.vue')['default']
    Pepe: typeof import('./src/components/Side/Nav/Pepe.vue')['default']
    RegisterForm: typeof import('./src/components/Auth/RegisterForm.vue')['default']
    ResetForm: typeof import('./src/components/Auth/ResetForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Form/Select.vue')['default']
    Side: typeof import('./src/components/Side/Side.vue')['default']
    TempLinks: typeof import('./src/components/Header/TempLinks.vue')['default']
    TextEditable: typeof import('./src/components/Form/TextEditable.vue')['default']
    TwoStepForm: typeof import('./src/components/Auth/TwoStepForm.vue')['default']
    User: typeof import('./src/components/Side/Nav/User/User.vue')['default']
  }
}
